// @generated by @trezor/protobuf/protoc-gen-plugin 1.0.0
// file: messages-ble.proto

import { type Static, Type } from '@trezor/schema-utils';

export type BleUnpair = Static<typeof BleUnpair>;
export const BleUnpair = Type.Object(
    {
        all: Type.Optional(Type.Boolean()),
        addr: Type.Optional(Type.String()),
    },
    { $id: 'BleUnpair' },
);
