// @generated by @trezor/protobuf/protoc-gen-plugin 1.0.0
// file: messages-ethereum-eip712.proto

import type { DescFile } from '@bufbuild/protobuf';

export declare const file_messages_ethereum_eip712: DescFile;
