// @generated by @trezor/protobuf/protoc-gen-plugin 1.0.0
// file: messages-management.proto

import type { DescFile } from '@bufbuild/protobuf';

export declare const file_messages_management: DescFile;
